<?php

use Illuminate\Database\Seeder;

class InventoryStockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>1,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>1,
            "reorder_level"=>5000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>2,
            "reorder_level"=>5000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>3,
            "reorder_level"=>5000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>4,
            "reorder_level"=>5000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>5,
            "reorder_level"=>5000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>6,
            "reorder_level"=>5000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>7,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>8,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>9,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>10,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>11,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>11,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>12,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>12,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>13,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>14,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>15,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>16,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>17,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>18,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>19,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>20,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>21,
            "reorder_level"=>3000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>22,
            "reorder_level"=>3000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>23,
            "reorder_level"=>3000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>24,
            "reorder_level"=>3000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>25,
            "reorder_level"=>3000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>26,
            "reorder_level"=>3000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>27,
            "reorder_level"=>3000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>28,
            "reorder_level"=>3000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>29,
            "reorder_level"=>3000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>30,
            "reorder_level"=>3000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>31,
            "reorder_level"=>3000
        ]);



    }
}
