<?php

use Illuminate\Database\Seeder;

class InventoryProductPromotionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>1,
            "items_number"=>20,
            "price"=>25000,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>2,
            "items_number"=>20,
            "price"=>25000,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>3,
            "items_number"=>20,
            "price"=>25000,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>4,
            "items_number"=>20,
            "price"=>25000,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>5,
            "items_number"=>20,
            "price"=>500,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>6,
            "items_number"=>12,
            "price"=>1000,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>7,
            "items_number"=>10,
            "price"=>1700,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>8,
            "items_number"=>20,
            "price"=>500,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>9,
            "items_number"=>12,
            "price"=>1000,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>10,
            "items_number"=>10,
            "price"=>1700,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>11,
            "items_number"=>20,
            "price"=>500,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>12,
            "items_number"=>12,
            "price"=>1000,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>13,
            "items_number"=>10,
            "price"=>1700,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>14,
            "items_number"=>20,
            "price"=>500,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>15,
            "items_number"=>12,
            "price"=>1000,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>16,
            "items_number"=>10,
            "price"=>1700,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>17,
            "items_number"=>20,
            "price"=>500,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>18,
            "items_number"=>12,
            "price"=>1000,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>19,
            "items_number"=>10,
            "price"=>1700,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>20,
            "items_number"=>20,
            "price"=>500,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>21,
            "items_number"=>12,
            "price"=>1000,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
        DB::table('inventory_product_promotions')->insert([
            "product_variety_id"=>22,
            "items_number"=>10,
            "price"=>1700,
            "from_date"=>"2018-10-02",
            "to_date"=>"2018-10-04"
        ]);
    }
}
