<?php

use Illuminate\Database\Seeder;

class InventoryStockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>1,
            "warehouse_id"=>1,
            "stock_level"=>10000,
            "reorder_level"=>2000
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>1,
            "warehouse_id"=>2,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>2,
            "warehouse_id"=>1,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>2,
            "warehouse_id"=>2,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>3,
            "warehouse_id"=>1,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>3,
            "warehouse_id"=>2,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>4,
            "warehouse_id"=>1,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>4,
            "warehouse_id"=>2,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>6,
            "warehouse_id"=>1,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>6,
            "warehouse_id"=>2,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>7,
            "warehouse_id"=>1,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>7,
            "warehouse_id"=>2,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>8,
            "warehouse_id"=>1,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>8,
            "warehouse_id"=>2,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>9,
            "warehouse_id"=>1,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>9,
            "warehouse_id"=>2,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>10,
            "warehouse_id"=>1,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>10,
            "warehouse_id"=>2,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>11,
            "warehouse_id"=>1,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);
        DB::table('inventory_stocks')->insert([
            "product_variety_id"=>11,
            "warehouse_id"=>2,
            "stock_level"=>5000,
            "reorder_level"=>500
        ]);

    }
}
