<?php

use Illuminate\Database\Seeder;

class InventoryDiscountVarietySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>1,
            "discount_id"=>1
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>1,
            "discount_id"=>2
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>1,
            "discount_id"=>3
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>4,
            "discount_id"=>1
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>4,
            "discount_id"=>2
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>4,
            "discount_id"=>3
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>3,
            "discount_id"=>1
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>3,
            "discount_id"=>2
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>3,
            "discount_id"=>3
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>1,
            "discount_id"=>1
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>5,
            "discount_id"=>4
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>8,
            "discount_id"=>4
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>11,
            "discount_id"=>4
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>14,
            "discount_id"=>4
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>17,
            "discount_id"=>4
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>20,
            "discount_id"=>4
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>6,
            "discount_id"=>5
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>9,
            "discount_id"=>5
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>12,
            "discount_id"=>5
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>15,
            "discount_id"=>5
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>18,
            "discount_id"=>5
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>21,
            "discount_id"=>5
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>7,
            "discount_id"=>6
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>10,
            "discount_id"=>5
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>13,
            "discount_id"=>5
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>16,
            "discount_id"=>5
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>19,
            "discount_id"=>5
        ]);
        DB::table('inventory_variety_discount')->insert([
            "product_variety_id"=>22,
            "discount_id"=>5
        ]);


    }
}
