<?php

use Illuminate\Database\Seeder;

class InventoryOrderInfoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>1,
            "product_variety_id"=>1,
            "lead_time"=>2
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>1,
            "product_variety_id"=>2,
            "lead_time"=>2
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>2,
            "product_variety_id"=>3,
            "lead_time"=>2
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>2,
            "product_variety_id"=>4,
            "lead_time"=>2
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>2,
            "product_variety_id"=>5,
            "lead_time"=>3
        ]);
        DB::table('inventory_order_infos')->insert([
            "product_variety_id"=>2,
            "supplier_id"=>6,
            "lead_time"=>3
        ]);

        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>2,
            "product_variety_id"=>7,
            "lead_time"=>3
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>2,
            "product_variety_id"=>8,
            "lead_time"=>3
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>3,
            "product_variety_id"=>9,
            "lead_time"=>3
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>3,
            "product_variety_id"=>10,
            "lead_time"=>3
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>3,
            "product_variety_id"=>11,
            "lead_time"=>3
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>3,
            "product_variety_id"=>12,
            "lead_time"=>4
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>3,
            "product_variety_id"=>13,
            "lead_time"=>4
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>3,
            "product_variety_id"=>14,
            "lead_time"=>4
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>1,
            "product_variety_id"=>15,
            "lead_time"=>4
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>1,
            "product_variety_id"=>16,
            "lead_time"=>4
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>4,
            "product_variety_id"=>17,
            "lead_time"=>4
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>4,
            "product_variety_id"=>18,
            "lead_time"=>1
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>2,
            "product_variety_id"=>19,
            "lead_time"=>1
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>2,
            "product_variety_id"=>20,
            "lead_time"=>1
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>3,
            "product_variety_id"=>21,
            "lead_time"=>1
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>4,
            "product_variety_id"=>22,
            "lead_time"=>1
        ]);
        DB::table('inventory_order_infos')->insert([
            "supplier_id"=>3,
            "product_variety_id"=>23,
            "lead_time"=>1
        ]);
    }
}
